export const path = {
  "勇者的坚定": "/Image/ExpressionDifference/TendouAris/初始立绘/勇者的坚定.webp",
  "坏了坏了_吃惊": "/Image/ExpressionDifference/TendouAris/初始立绘/坏了坏了_吃惊.webp",
  "坏了坏了_完蛋了": "/Image/ExpressionDifference/TendouAris/初始立绘/坏了坏了_完蛋了.webp",
  "坏了坏了_担心": "/Image/ExpressionDifference/TendouAris/初始立绘/坏了坏了_担心.webp",
  "平静": "/Image/ExpressionDifference/TendouAris/初始立绘/平静.webp",
  "平静_睁眼1": "/Image/ExpressionDifference/TendouAris/初始立绘/平静_睁眼1.webp",
  "平静_睁眼2": "/Image/ExpressionDifference/TendouAris/初始立绘/平静_睁眼2.webp",
  "开心地笑": "/Image/ExpressionDifference/TendouAris/初始立绘/开心地笑.webp",
  "开心地笑_睁眼": "/Image/ExpressionDifference/TendouAris/初始立绘/开心地笑_睁眼.webp",
  "微笑": "/Image/ExpressionDifference/TendouAris/初始立绘/微笑.webp",
  "感动": "/Image/ExpressionDifference/TendouAris/初始立绘/感动.webp",
  "掉小珍珠了_眯眼": "/Image/ExpressionDifference/TendouAris/初始立绘/掉小珍珠了_眯眼.webp",
  "掉小珍珠了_睁眼": "/Image/ExpressionDifference/TendouAris/初始立绘/掉小珍珠了_睁眼.webp",
  "柯伊_啊_疑问": "/Image/ExpressionDifference/TendouAris/初始立绘/柯伊_啊_疑问.webp",
  "柯伊_啊_疑问_黑脸": "/Image/ExpressionDifference/TendouAris/初始立绘/柯伊_啊_疑问_黑脸.webp",
  "柯伊_嗯_疑问": "/Image/ExpressionDifference/TendouAris/初始立绘/柯伊_嗯_疑问.webp",
  "柯伊_嗯_疑问_黑脸": "/Image/ExpressionDifference/TendouAris/初始立绘/柯伊_嗯_疑问_黑脸.webp",
  "柯伊_平静": "/Image/ExpressionDifference/TendouAris/初始立绘/柯伊_平静.webp",
  "柯伊_平静_黑脸": "/Image/ExpressionDifference/TendouAris/初始立绘/柯伊_平静_黑脸.webp",
  "柯伊_平静_黑脸2": "/Image/ExpressionDifference/TendouAris/初始立绘/柯伊_平静_黑脸2.webp",
  "难堪": "/Image/ExpressionDifference/TendouAris/初始立绘/难堪.webp"
} as const;
