export const path = {
  "伤心": "/Image/ExpressionDifference/TendouAris/武装_战损/伤心.webp",
  "伤心_睁眼": "/Image/ExpressionDifference/TendouAris/武装_战损/伤心_睁眼.webp",
  "伤心_睁眼2": "/Image/ExpressionDifference/TendouAris/武装_战损/伤心_睁眼2.webp",
  "坏了_完蛋了": "/Image/ExpressionDifference/TendouAris/武装_战损/坏了_完蛋了.webp",
  "坏了_担心": "/Image/ExpressionDifference/TendouAris/武装_战损/坏了_担心.webp",
  "平静_哦": "/Image/ExpressionDifference/TendouAris/武装_战损/平静_哦.webp",
  "平静_睁眼": "/Image/ExpressionDifference/TendouAris/武装_战损/平静_睁眼.webp",
  "平静_睁眼2": "/Image/ExpressionDifference/TendouAris/武装_战损/平静_睁眼2.webp",
  "平静_睁眼3": "/Image/ExpressionDifference/TendouAris/武装_战损/平静_睁眼3.webp",
  "平静_闭眼": "/Image/ExpressionDifference/TendouAris/武装_战损/平静_闭眼.webp",
  "幸福": "/Image/ExpressionDifference/TendouAris/武装_战损/幸福.webp",
  "幸福_睁眼": "/Image/ExpressionDifference/TendouAris/武装_战损/幸福_睁眼.webp",
  "开心地笑": "/Image/ExpressionDifference/TendouAris/武装_战损/开心地笑.webp",
  "开心地笑_睁眼": "/Image/ExpressionDifference/TendouAris/武装_战损/开心地笑_睁眼.webp",
  "微笑": "/Image/ExpressionDifference/TendouAris/武装_战损/微笑.webp",
  "微笑_闭眼": "/Image/ExpressionDifference/TendouAris/武装_战损/微笑_闭眼.webp",
  "担忧": "/Image/ExpressionDifference/TendouAris/武装_战损/担忧.webp",
  "痛哭": "/Image/ExpressionDifference/TendouAris/武装_战损/痛哭.webp",
  "自信_我们上吧": "/Image/ExpressionDifference/TendouAris/武装_战损/自信_我们上吧.webp",
  "认真严肃_基础": "/Image/ExpressionDifference/TendouAris/武装_战损/认真严肃_基础.webp",
  "认真严肃_基础2": "/Image/ExpressionDifference/TendouAris/武装_战损/认真严肃_基础2.webp",
  "认真严肃_张嘴": "/Image/ExpressionDifference/TendouAris/武装_战损/认真严肃_张嘴.webp",
  "认真严肃_自信地微笑": "/Image/ExpressionDifference/TendouAris/武装_战损/认真严肃_自信地微笑.webp"
} as const;
