export const path = {
  "严肃_睁眼": "/Image/ExpressionDifference/TendouKei/神名十文字/严肃_睁眼.webp",
  "严肃_闭眼": "/Image/ExpressionDifference/TendouKei/神名十文字/严肃_闭眼.webp",
  "严肃_闭眼2": "/Image/ExpressionDifference/TendouKei/神名十文字/严肃_闭眼2.webp",
  "唉": "/Image/ExpressionDifference/TendouKei/神名十文字/唉.webp",
  "平静_睁眼": "/Image/ExpressionDifference/TendouKei/神名十文字/平静_睁眼.webp",
  "平静_睁眼2": "/Image/ExpressionDifference/TendouKei/神名十文字/平静_睁眼2.webp",
  "平静_睁眼3": "/Image/ExpressionDifference/TendouKei/神名十文字/平静_睁眼3.webp",
  "平静_睁眼4": "/Image/ExpressionDifference/TendouKei/神名十文字/平静_睁眼4.webp",
  "平静_睁眼5": "/Image/ExpressionDifference/TendouKei/神名十文字/平静_睁眼5.webp",
  "平静_闭眼": "/Image/ExpressionDifference/TendouKei/神名十文字/平静_闭眼.webp",
  "开心地笑_闭眼": "/Image/ExpressionDifference/TendouKei/神名十文字/开心地笑_闭眼.webp",
  "开心地笑_闭眼2": "/Image/ExpressionDifference/TendouKei/神名十文字/开心地笑_闭眼2.webp",
  "微笑_睁眼": "/Image/ExpressionDifference/TendouKei/神名十文字/微笑_睁眼.webp",
  "微笑_闭眼": "/Image/ExpressionDifference/TendouKei/神名十文字/微笑_闭眼.webp",
  "惊讶_基础": "/Image/ExpressionDifference/TendouKei/神名十文字/惊讶_基础.webp",
  "惊讶_基础2": "/Image/ExpressionDifference/TendouKei/神名十文字/惊讶_基础2.webp",
  "生气_呵斥": "/Image/ExpressionDifference/TendouKei/神名十文字/生气_呵斥.webp",
  "生气_咬牙切齿": "/Image/ExpressionDifference/TendouKei/神名十文字/生气_咬牙切齿.webp",
  "生气_咬牙切齿_流泪": "/Image/ExpressionDifference/TendouKei/神名十文字/生气_咬牙切齿_流泪.webp",
  "生气_咬牙切齿_流泪更甚": "/Image/ExpressionDifference/TendouKei/神名十文字/生气_咬牙切齿_流泪更甚.webp",
  "生气_快给我闭嘴啊": "/Image/ExpressionDifference/TendouKei/神名十文字/生气_快给我闭嘴啊.webp",
  "生气_更生气_呵斥": "/Image/ExpressionDifference/TendouKei/神名十文字/生气_更生气_呵斥.webp"
} as const;
